[package]
edition = "2018"
name = "example_ranking_index_integrity"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]
name = "example_ranking_index_integrity"

[dependencies]
serde = "1"
hdi = "=0.1.10"
